<?php

namespace App\Traits\Main;

trait PrisonerMessageTrait
{
    protected array $messages = [
        'name.required'=>'o campo é obrigatório',
        'name.max'=>'o campo deve ter no máximo 100 caracteres',
        'nickname.max'=>'o campo deve ter no máximo 100 caracteres',
        'date_birth.riquired'=>'o campo é obrigatório',
        'date_birth.max'=>'o campo deve ter no máximo 10 caracteres',
        'date_birth.min'=>'o campo deve ter no mínimo 10 caracteres',
        'cpf.max'=>'o campo deve ter no máximo 14 caracteres',
        'cpf.min'=>'o campo deve ter no mínimo 14 caracteres',
        'cpf.unique'=>'o campo deve ser único',
        'rg.max'=>'o campo deve ter no máximo 50 caracteres',
        'rg.unique'=>'o campo deve ser único',
        'title.max'=>'o campo deve ter no máximo 14 caracteres',
        'title.min'=>'o campo deve ter no mínimo 14 caracteres',
        'title.unique'=>'o campo deve ser único',
        'birth_certificate.max'=>'o campo deve ter no máximo 60 caracteres',
        'birth_certificate.unique'=>'o campo deve ser único',
        'reservist.max'=>'o campo deve ter no máximo 60 caracteres',
        'reservist.unique'=>'o campo deve ser único',
        'sus_card.max'=>'o campo deve ter no máximo 19 caracteres',
        'sus_card.min'=>'o campo deve ter no mínimo 19 caracteres',
        'sus_card.unique'=>'o campo deve ser único',
        'rji.max'=>'o campo deve ter no máximo 12 caracteres',
        'rji.min'=>'o campo deve ter no mínimo 12 caracteres',
        'rji.unique'=>'o campo deve ser único',
        'profession.max'=>'o campo deve ter no máximo 100 caracteres',
        'mother.max'=>'o campo deve ter no máximo 100 caracteres',
        'father.max'=>'o campo deve ter no máximo 100 caracteres',
        'status_prison_id.max'=>'o campo deve ter no máximo 10 caracteres',
        'status_prison_id.required'=>'o campo é obrigatório',
        'education_level_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'education_level_id.required'=>'o campo é obrigatório',
        'civil_status_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'civil_status_id.required'=>'o campo é obrigatório',
        'sex_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'sex_id.required'=>'o campo é obrigatório',
        'sexual_orientation_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'sexual_orientation_id.required'=>'o campo é obrigatório',
        'ethnicity_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'ethnicity_id.required'=>'o campo é obrigatório',
        'municipality_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'municipality_id.required'=>'o campo é obrigatório',
        'country_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'country_id.required'=>'o campo é obrigatório',
        'state_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'state_id.required'=>'o campo é obrigatório',
        'prison_unit_id.max'=>'o campo deve ter no máximo 20 caracteres',
        'prison_unit_id.required'=>'o campo é obrigatório',
        'user_create.max'=>'o campo deve ter no máximo 10 caracteres',
        'user_create.required'=>'o campo é obrigatório',
    ];
}
